import type { GatewayConfig } from "./config.js";
export type IncomingDirectMessage={senderId:string;conversationId:string;messageId:string;text:string}; export type IncomingGroupMessage={groupId:string;messageId:string;senderId:string;senderName:string;text:string;sentAtMs:number}; export type OutboxItem={id:number;content:string};
const headers=(c:GatewayConfig)=>({"content-type":"application/json","x-zalo-bridge-secret":c.bridgeSecret});
async function checked(r:Response,label:string){if(!r.ok)throw new Error(`${label} returned ${r.status}: ${(await r.text()).slice(0,200)}`);return r;}
export async function loadSavedSession(c:GatewayConfig){const r=await fetch(`${c.bridgeBaseUrl}/session`,{headers:headers(c)});return await (await checked(r,"Session load")).json() as any;}
export async function saveSession(c:GatewayConfig,s:any){await checked(await fetch(`${c.bridgeBaseUrl}/session`,{method:"PUT",headers:headers(c),body:JSON.stringify(s)}),"Session save");}
export async function clearSession(c:GatewayConfig){await checked(await fetch(`${c.bridgeBaseUrl}/session`,{method:"DELETE",headers:headers(c)}),"Session clear");}
export async function callBridge(c:GatewayConfig,m:IncomingDirectMessage){const r=await fetch(`${c.bridgeBaseUrl}/message`,{method:"POST",headers:headers(c),body:JSON.stringify({account_id:c.accountId,sender_id:m.senderId,conversation_id:m.conversationId,message_id:m.messageId,text:m.text}),signal:AbortSignal.timeout(240000)});return await (await checked(r,"Bridge")).json() as any;}
export async function fetchAllowedGroups(c:GatewayConfig){const r=await fetch(`${c.bridgeBaseUrl}/groups/${encodeURIComponent(c.accountId)}`,{headers:headers(c)});const g=await (await checked(r,"Groups")).json() as any[];return new Set(g.map(x=>String(x.group_id)));}
export async function storeGroupMessage(c:GatewayConfig,m:IncomingGroupMessage){await checked(await fetch(`${c.bridgeBaseUrl}/group-message`,{method:"POST",headers:headers(c),body:JSON.stringify({account_id:c.accountId,group_id:m.groupId,message_id:m.messageId,sender_id:m.senderId,sender_name:m.senderName,text:m.text,sent_at_ms:m.sentAtMs})}),"Group message");}
export async function fetchOutbox(c:GatewayConfig){const r=await fetch(`${c.bridgeBaseUrl}/outbox/${encodeURIComponent(c.accountId)}/${encodeURIComponent(c.controllerId)}`,{headers:headers(c)});return await (await checked(r,"Outbox")).json() as OutboxItem[];}
export async function ackOutbox(c:GatewayConfig,id:number){await checked(await fetch(`${c.bridgeBaseUrl}/outbox/${id}/ack`,{method:"POST",headers:headers(c)}),"Ack");}
